### Introduction for Python

This is a Jupyter notebook, which can contain multiple contents, including text, Python code and output results. We expect to you to read and run the code to get familiar with Python.

To run the code, either press Shift + Enter or click the triangle ▸ button.

Additional reading: https://docs.python.org/3/tutorial/introduction.html

In [ ]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Print something
print('Hello, world!')

In [ ]:
# Add two numbers
a = 1
b = 1
c = a + b
print('{0} + {1} = {2}'.format(a, b, c))

In [ ]:
# Data structure: list
a = ['spam', 'eggs', 100, 1234, 2*2]

# Index a list
print(a[0])

# Slice a list
print(a[:2])
print(a[:-1])

In [ ]:
# List comprehension
a = [1, 2, 3, 4, 5]
b = [x * x for x in a]
print('a =', a)
print('b =', b)

In [ ]:
# Data structure: dictionary
dial_code = {'US': 1,
             'AT': 43,
             'UK': 44,
             'DK': 45}
print(dial_code['UK'])

In [ ]:
# if statement
x = -1
if x < 0:
    print('x is negative')
else:
    print('x is zero or positive')

In [ ]:
# for statement
for x in [0, 1, 2, 3]:
    print('x =', x)

In [ ]:
# Define a function
def fib(n):
    """ Return a Fibonacci series up to n. """
    # result is a list   
    result = []
    a, b = 0, 1
    
    # while statement
    while a < n:
        # Append a to the result list    
        result += [a]
        # Increment the Fibonacci series
        a, b = b, a+b
    
    # Return the result
    return result

In [ ]:
# Call the function
result = fib(100)
print(result)

In [ ]:
# Create a data array using numpy
x = np.array([1, 2, 3, 4, 5])
print(x)

In [ ]:
# Perform element-wise multiplication
y = x * x
print(y)

In [ ]:
# Plot a line
plt.plot(x, y)

In [26]:
# Array shape
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])
print(a)
print('a.shape =', a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a.shape = (3, 4)


In [27]:
# Array indexing
print(a[0, 0])

1


In [30]:
# Array slicing
print(a[1, :])

[5 6 7 8]


In [32]:
# Array slicing
print(a[1, :2])

[5 6]


In [33]:
# Matrix multiplication
b = np.array([[1],
              [1],
              [1]])
print(b)
print(b.shape)

c = np.dot(a, b)
print(c)

[[1]
 [1]
 [1]]
(3, 1)


ValueError: shapes (3,4) and (3,1) not aligned: 4 (dim 1) != 3 (dim 0)